a = input('Digite Algo: ')
print('O tipo primitivo do valor {} é {} '.format( a, type(a)))
print('O valor de {} só tem espaços? => {}'.format(a, a.isspace()))
print('O valor de {} é alfabético? => {}'.format( a,a.isalpha()))
print('O valor de {} é um número? => {}'.format(a, a.isnumeric()))
print('O valor de {} é alfanumerico? => {}'.format(a, a.isalnum()))
print('O valor de {} está em letras maiúsculas? => {}'.format(a, a.isupper()))
print('O valor de {} está em letras minúsculas? => {}'.format(a, a.islower()))
print('O valor de {} está capitalizado? => {}'.format(a, a.istitle()))